"""initial migration

Revision ID: 3d73081d9a3
Revises: None
Create Date: 2015-12-14 21:18:32.552834

"""

# revision identifiers, used by Alembic.
revision = '3d73081d9a3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
